/**
 * Text-translation language catalog (GPT Text Translation Language Catalog,
 * edition 2026-09-23; 343 entries across 10 regional groups).
 *
 * This describes practicality of *written* GPT text-to-text translation —
 * the Translate step in the workspace (`gpt-4.1-mini` by default). It does
 * NOT describe ElevenLabs voice/TTS language support, which is a much
 * smaller, separate list (see `elevenlabs-languages.ts`) — the source
 * document explicitly excludes transcription, speech recognition and
 * text-to-speech. Keep the two lists separate; do not use tiers here to
 * decide which ElevenLabs voices to show.
 */

export type TranslationTier = "STRONG" | "GOOD_PRACTICAL" | "EXPERIMENTAL_VERIFY";

export type TranslationLanguageEntry = {
  id: string;
  englishName: string;
  autonym: string;
  isoCode: string;
  regionGroup: string;
  primaryRegion: string;
  tier: TranslationTier;
};

export const TRANSLATION_TIER_LABEL: Record<TranslationTier, string> = {
  STRONG: "Strong",
  GOOD_PRACTICAL: "Good — practical",
  EXPERIMENTAL_VERIFY: "Experimental — verify"
};

/** What each tier means for product use, from the catalog's own "how to use" guidance. */
export const TRANSLATION_TIER_GUIDANCE: Record<TranslationTier, string> = {
  STRONG: "Suitable for broad use after normal QA — test scripts, common domains, names, numbers and both directions.",
  GOOD_PRACTICAL: "Enable after language-specific evaluation. Uncommon domains and dialects may need review; show a quality notice.",
  EXPERIMENTAL_VERIFY: "Treat as a pilot. Route through human review rather than publishing unverified translations."
};

export const TRANSLATION_LANGUAGE_CATALOG: TranslationLanguageEntry[] = [
  { id: "luganda", englishName: "Luganda", autonym: "Luganda", isoCode: "lg", regionGroup: "Uganda and the Great Lakes", primaryRegion: "Uganda", tier: "GOOD_PRACTICAL" },
  { id: "kinyarwanda", englishName: "Kinyarwanda", autonym: "Ikinyarwanda", isoCode: "rw", regionGroup: "Uganda and the Great Lakes", primaryRegion: "Rwanda and Great Lakes", tier: "GOOD_PRACTICAL" },
  { id: "kirundi", englishName: "Kirundi", autonym: "Ikirundi", isoCode: "rn", regionGroup: "Uganda and the Great Lakes", primaryRegion: "Burundi and Great Lakes", tier: "GOOD_PRACTICAL" },
  { id: "runyankole", englishName: "Runyankole", autonym: "Runyankore", isoCode: "nyn", regionGroup: "Uganda and the Great Lakes", primaryRegion: "Western Uganda", tier: "EXPERIMENTAL_VERIFY" },
  { id: "rukiga", englishName: "Rukiga", autonym: "Rukiga", isoCode: "cgg", regionGroup: "Uganda and the Great Lakes", primaryRegion: "Southwestern Uganda", tier: "EXPERIMENTAL_VERIFY" },
  { id: "runyoro", englishName: "Runyoro", autonym: "Runyoro", isoCode: "nyo", regionGroup: "Uganda and the Great Lakes", primaryRegion: "Western Uganda", tier: "EXPERIMENTAL_VERIFY" },
  { id: "rutooro", englishName: "Rutooro", autonym: "Rutooro", isoCode: "ttj", regionGroup: "Uganda and the Great Lakes", primaryRegion: "Western Uganda", tier: "EXPERIMENTAL_VERIFY" },
  { id: "lusoga", englishName: "Lusoga", autonym: "Lusoga", isoCode: "xog", regionGroup: "Uganda and the Great Lakes", primaryRegion: "Eastern Uganda", tier: "EXPERIMENTAL_VERIFY" },
  { id: "acholi", englishName: "Acholi", autonym: "Lwo", isoCode: "ach", regionGroup: "Uganda and the Great Lakes", primaryRegion: "Northern Uganda and South Sudan", tier: "EXPERIMENTAL_VERIFY" },
  { id: "lango", englishName: "Lango", autonym: "Leb Lango", isoCode: "laj", regionGroup: "Uganda and the Great Lakes", primaryRegion: "Northern Uganda", tier: "EXPERIMENTAL_VERIFY" },
  { id: "ateso", englishName: "Ateso", autonym: "Ateso", isoCode: "teo", regionGroup: "Uganda and the Great Lakes", primaryRegion: "Eastern Uganda and Kenya", tier: "EXPERIMENTAL_VERIFY" },
  { id: "dhopadhola", englishName: "Dhopadhola", autonym: "Dhopadhola", isoCode: "adh", regionGroup: "Uganda and the Great Lakes", primaryRegion: "Eastern Uganda", tier: "EXPERIMENTAL_VERIFY" },
  { id: "lumasaba", englishName: "Lumasaba", autonym: "Lumasaba", isoCode: "myx", regionGroup: "Uganda and the Great Lakes", primaryRegion: "Eastern Uganda", tier: "EXPERIMENTAL_VERIFY" },
  { id: "lugwere", englishName: "Lugwere", autonym: "Lugwere", isoCode: "gwr", regionGroup: "Uganda and the Great Lakes", primaryRegion: "Eastern Uganda", tier: "EXPERIMENTAL_VERIFY" },
  { id: "lugbara", englishName: "Lugbara", autonym: "Lugbara", isoCode: "lgg", regionGroup: "Uganda and the Great Lakes", primaryRegion: "Northwestern Uganda and DR Congo", tier: "EXPERIMENTAL_VERIFY" },
  { id: "alur", englishName: "Alur", autonym: "Dho Alur", isoCode: "alz", regionGroup: "Uganda and the Great Lakes", primaryRegion: "Uganda and DR Congo", tier: "EXPERIMENTAL_VERIFY" },
  { id: "kumam", englishName: "Kumam", autonym: "Ikumama", isoCode: "kdi", regionGroup: "Uganda and the Great Lakes", primaryRegion: "Eastern Uganda", tier: "EXPERIMENTAL_VERIFY" },
  { id: "karamojong", englishName: "Karamojong", autonym: "Ngakarimojong", isoCode: "kdj", regionGroup: "Uganda and the Great Lakes", primaryRegion: "Northeastern Uganda", tier: "EXPERIMENTAL_VERIFY" },
  { id: "kupsapi", englishName: "Kupsapi", autonym: "Kupsabiny", isoCode: "kpz", regionGroup: "Uganda and the Great Lakes", primaryRegion: "Eastern Uganda", tier: "EXPERIMENTAL_VERIFY" },
  { id: "ik", englishName: "Ik", autonym: "Icetod", isoCode: "ikx", regionGroup: "Uganda and the Great Lakes", primaryRegion: "Northeastern Uganda", tier: "EXPERIMENTAL_VERIFY" },
  { id: "ma-di", englishName: "Ma'di", autonym: "Madi", isoCode: "mhi", regionGroup: "Uganda and the Great Lakes", primaryRegion: "Uganda and South Sudan", tier: "EXPERIMENTAL_VERIFY" },
  { id: "kakwa", englishName: "Kakwa", autonym: "Kakwa", isoCode: "keo", regionGroup: "Uganda and the Great Lakes", primaryRegion: "Uganda and South Sudan", tier: "EXPERIMENTAL_VERIFY" },
  { id: "aringa", englishName: "Aringa", autonym: "Aringa", isoCode: "luc", regionGroup: "Uganda and the Great Lakes", primaryRegion: "Northwestern Uganda", tier: "EXPERIMENTAL_VERIFY" },
  { id: "ndrulo", englishName: "Ndrulo", autonym: "Ndrulo", isoCode: "dno", regionGroup: "Uganda and the Great Lakes", primaryRegion: "Western Uganda and DR Congo", tier: "EXPERIMENTAL_VERIFY" },
  { id: "amba", englishName: "Amba", autonym: "Kihamba", isoCode: "rwm", regionGroup: "Uganda and the Great Lakes", primaryRegion: "Western Uganda and DR Congo", tier: "EXPERIMENTAL_VERIFY" },
  { id: "konzo", englishName: "Konzo", autonym: "Lhukonzo", isoCode: "koo", regionGroup: "Uganda and the Great Lakes", primaryRegion: "Uganda and DR Congo", tier: "EXPERIMENTAL_VERIFY" },
  { id: "rufumbira", englishName: "Rufumbira", autonym: "Rufumbira", isoCode: "rw", regionGroup: "Uganda and the Great Lakes", primaryRegion: "Southwestern Uganda", tier: "EXPERIMENTAL_VERIFY" },
  { id: "nyole", englishName: "Nyole", autonym: "Lunyole", isoCode: "nuj", regionGroup: "Uganda and the Great Lakes", primaryRegion: "Eastern Uganda", tier: "EXPERIMENTAL_VERIFY" },
  { id: "samia", englishName: "Samia", autonym: "Lusamia", isoCode: "lsm", regionGroup: "Uganda and the Great Lakes", primaryRegion: "Uganda and Kenya", tier: "EXPERIMENTAL_VERIFY" },
  { id: "swahili", englishName: "Swahili", autonym: "Kiswahili", isoCode: "sw", regionGroup: "Uganda and the Great Lakes", primaryRegion: "East and Central Africa", tier: "STRONG" },
  { id: "lingala", englishName: "Lingala", autonym: "Lingala", isoCode: "ln", regionGroup: "Uganda and the Great Lakes", primaryRegion: "DR Congo and Central Africa", tier: "GOOD_PRACTICAL" },
  { id: "somali", englishName: "Somali", autonym: "Soomaali", isoCode: "so", regionGroup: "East Africa and the Horn", primaryRegion: "Somalia and Horn of Africa", tier: "GOOD_PRACTICAL" },
  { id: "amharic", englishName: "Amharic", autonym: "Amarinna", isoCode: "am", regionGroup: "East Africa and the Horn", primaryRegion: "Ethiopia", tier: "STRONG" },
  { id: "oromo", englishName: "Oromo", autonym: "Afaan Oromoo", isoCode: "om", regionGroup: "East Africa and the Horn", primaryRegion: "Ethiopia and Kenya", tier: "GOOD_PRACTICAL" },
  { id: "tigrinya", englishName: "Tigrinya", autonym: "Tigrinya", isoCode: "ti", regionGroup: "East Africa and the Horn", primaryRegion: "Eritrea and Ethiopia", tier: "GOOD_PRACTICAL" },
  { id: "afar", englishName: "Afar", autonym: "Qafar af", isoCode: "aa", regionGroup: "East Africa and the Horn", primaryRegion: "Djibouti, Eritrea and Ethiopia", tier: "EXPERIMENTAL_VERIFY" },
  { id: "harari", englishName: "Harari", autonym: "Gey Sinan", isoCode: "har", regionGroup: "East Africa and the Horn", primaryRegion: "Ethiopia", tier: "EXPERIMENTAL_VERIFY" },
  { id: "sidamo", englishName: "Sidamo", autonym: "Sidaamu Afoo", isoCode: "sid", regionGroup: "East Africa and the Horn", primaryRegion: "Ethiopia", tier: "EXPERIMENTAL_VERIFY" },
  { id: "wolaytta", englishName: "Wolaytta", autonym: "Wolayttatto Doonaa", isoCode: "wal", regionGroup: "East Africa and the Horn", primaryRegion: "Ethiopia", tier: "EXPERIMENTAL_VERIFY" },
  { id: "hadiyya", englishName: "Hadiyya", autonym: "Hadiyyisa", isoCode: "hdy", regionGroup: "East Africa and the Horn", primaryRegion: "Ethiopia", tier: "EXPERIMENTAL_VERIFY" },
  { id: "gamo", englishName: "Gamo", autonym: "Gamotso", isoCode: "gmv", regionGroup: "East Africa and the Horn", primaryRegion: "Ethiopia", tier: "EXPERIMENTAL_VERIFY" },
  { id: "kamba", englishName: "Kamba", autonym: "Kikamba", isoCode: "kam", regionGroup: "East Africa and the Horn", primaryRegion: "Kenya", tier: "EXPERIMENTAL_VERIFY" },
  { id: "kikuyu", englishName: "Kikuyu", autonym: "Gikuyu", isoCode: "ki", regionGroup: "East Africa and the Horn", primaryRegion: "Kenya", tier: "GOOD_PRACTICAL" },
  { id: "luo", englishName: "Luo", autonym: "Dholuo", isoCode: "luo", regionGroup: "East Africa and the Horn", primaryRegion: "Kenya and Tanzania", tier: "GOOD_PRACTICAL" },
  { id: "kalenjin", englishName: "Kalenjin", autonym: "Kalenjin", isoCode: "kln", regionGroup: "East Africa and the Horn", primaryRegion: "Kenya", tier: "EXPERIMENTAL_VERIFY" },
  { id: "maasai", englishName: "Maasai", autonym: "Maa", isoCode: "mas", regionGroup: "East Africa and the Horn", primaryRegion: "Kenya and Tanzania", tier: "EXPERIMENTAL_VERIFY" },
  { id: "meru", englishName: "Meru", autonym: "Kimeru", isoCode: "mer", regionGroup: "East Africa and the Horn", primaryRegion: "Kenya", tier: "EXPERIMENTAL_VERIFY" },
  { id: "embu", englishName: "Embu", autonym: "Kiembu", isoCode: "ebu", regionGroup: "East Africa and the Horn", primaryRegion: "Kenya", tier: "EXPERIMENTAL_VERIFY" },
  { id: "taita", englishName: "Taita", autonym: "Kitaita", isoCode: "dav", regionGroup: "East Africa and the Horn", primaryRegion: "Kenya", tier: "EXPERIMENTAL_VERIFY" },
  { id: "turkana", englishName: "Turkana", autonym: "Ng'aturkana", isoCode: "tuv", regionGroup: "East Africa and the Horn", primaryRegion: "Kenya", tier: "EXPERIMENTAL_VERIFY" },
  { id: "borana-oromo", englishName: "Borana Oromo", autonym: "Afaan Oromoo Boranaa", isoCode: "gax", regionGroup: "East Africa and the Horn", primaryRegion: "Ethiopia and Kenya", tier: "EXPERIMENTAL_VERIFY" },
  { id: "samburu", englishName: "Samburu", autonym: "Sampur", isoCode: "saq", regionGroup: "East Africa and the Horn", primaryRegion: "Kenya", tier: "EXPERIMENTAL_VERIFY" },
  { id: "gusii", englishName: "Gusii", autonym: "Ekegusii", isoCode: "guz", regionGroup: "East Africa and the Horn", primaryRegion: "Kenya", tier: "EXPERIMENTAL_VERIFY" },
  { id: "chaga", englishName: "Chaga", autonym: "Kichaga", isoCode: "jmc", regionGroup: "East Africa and the Horn", primaryRegion: "Tanzania", tier: "EXPERIMENTAL_VERIFY" },
  { id: "sukuma", englishName: "Sukuma", autonym: "Kisukuma", isoCode: "suk", regionGroup: "East Africa and the Horn", primaryRegion: "Tanzania", tier: "EXPERIMENTAL_VERIFY" },
  { id: "nyamwezi", englishName: "Nyamwezi", autonym: "Kinyamwezi", isoCode: "nym", regionGroup: "East Africa and the Horn", primaryRegion: "Tanzania", tier: "EXPERIMENTAL_VERIFY" },
  { id: "haya", englishName: "Haya", autonym: "Kihaya", isoCode: "hay", regionGroup: "East Africa and the Horn", primaryRegion: "Tanzania", tier: "EXPERIMENTAL_VERIFY" },
  { id: "hehe", englishName: "Hehe", autonym: "Kihehe", isoCode: "heh", regionGroup: "East Africa and the Horn", primaryRegion: "Tanzania", tier: "EXPERIMENTAL_VERIFY" },
  { id: "makonde", englishName: "Makonde", autonym: "Chimakonde", isoCode: "kde", regionGroup: "East Africa and the Horn", primaryRegion: "Tanzania and Mozambique", tier: "EXPERIMENTAL_VERIFY" },
  { id: "comorian", englishName: "Comorian", autonym: "Shikomori", isoCode: "zdj", regionGroup: "East Africa and the Horn", primaryRegion: "Comoros", tier: "EXPERIMENTAL_VERIFY" },
  { id: "malagasy", englishName: "Malagasy", autonym: "Malagasy", isoCode: "mg", regionGroup: "East Africa and the Horn", primaryRegion: "Madagascar", tier: "GOOD_PRACTICAL" },
  { id: "seychellois-creole", englishName: "Seychellois Creole", autonym: "Kreol Seselwa", isoCode: "crs", regionGroup: "East Africa and the Horn", primaryRegion: "Seychelles", tier: "GOOD_PRACTICAL" },
  { id: "mauritian-creole", englishName: "Mauritian Creole", autonym: "Kreol Morisien", isoCode: "mfe", regionGroup: "East Africa and the Horn", primaryRegion: "Mauritius", tier: "GOOD_PRACTICAL" },
  { id: "hausa", englishName: "Hausa", autonym: "Hausa", isoCode: "ha", regionGroup: "West Africa and the Sahel", primaryRegion: "West Africa and Sahel", tier: "STRONG" },
  { id: "yoruba", englishName: "Yoruba", autonym: "Yoruba", isoCode: "yo", regionGroup: "West Africa and the Sahel", primaryRegion: "Nigeria and Benin", tier: "STRONG" },
  { id: "igbo", englishName: "Igbo", autonym: "Igbo", isoCode: "ig", regionGroup: "West Africa and the Sahel", primaryRegion: "Nigeria", tier: "GOOD_PRACTICAL" },
  { id: "fula", englishName: "Fula", autonym: "Fulfulde", isoCode: "ff", regionGroup: "West Africa and the Sahel", primaryRegion: "West Africa and Sahel", tier: "GOOD_PRACTICAL" },
  { id: "wolof", englishName: "Wolof", autonym: "Wolof", isoCode: "wo", regionGroup: "West Africa and the Sahel", primaryRegion: "Senegal and Gambia", tier: "GOOD_PRACTICAL" },
  { id: "bambara", englishName: "Bambara", autonym: "Bamanankan", isoCode: "bm", regionGroup: "West Africa and the Sahel", primaryRegion: "Mali", tier: "GOOD_PRACTICAL" },
  { id: "akan", englishName: "Akan", autonym: "Akan", isoCode: "ak", regionGroup: "West Africa and the Sahel", primaryRegion: "Ghana and Ivory Coast", tier: "GOOD_PRACTICAL" },
  { id: "twi", englishName: "Twi", autonym: "Twi", isoCode: "tw", regionGroup: "West Africa and the Sahel", primaryRegion: "Ghana", tier: "GOOD_PRACTICAL" },
  { id: "ewe", englishName: "Ewe", autonym: "Ewegbe", isoCode: "ee", regionGroup: "West Africa and the Sahel", primaryRegion: "Ghana and Togo", tier: "GOOD_PRACTICAL" },
  { id: "ga", englishName: "Ga", autonym: "Gaa", isoCode: "gaa", regionGroup: "West Africa and the Sahel", primaryRegion: "Ghana", tier: "EXPERIMENTAL_VERIFY" },
  { id: "dagbani", englishName: "Dagbani", autonym: "Dagbanli", isoCode: "dag", regionGroup: "West Africa and the Sahel", primaryRegion: "Ghana", tier: "EXPERIMENTAL_VERIFY" },
  { id: "dagaare", englishName: "Dagaare", autonym: "Dagaare", isoCode: "dga", regionGroup: "West Africa and the Sahel", primaryRegion: "Ghana and Burkina Faso", tier: "EXPERIMENTAL_VERIFY" },
  { id: "mossi", englishName: "Mossi", autonym: "Moore", isoCode: "mos", regionGroup: "West Africa and the Sahel", primaryRegion: "Burkina Faso", tier: "EXPERIMENTAL_VERIFY" },
  { id: "dyula", englishName: "Dyula", autonym: "Julakan", isoCode: "dyu", regionGroup: "West Africa and the Sahel", primaryRegion: "Ivory Coast and Burkina Faso", tier: "EXPERIMENTAL_VERIFY" },
  { id: "mandinka", englishName: "Mandinka", autonym: "Mandinka kango", isoCode: "mnk", regionGroup: "West Africa and the Sahel", primaryRegion: "Gambia, Senegal and Guinea", tier: "EXPERIMENTAL_VERIFY" },
  { id: "maninka", englishName: "Maninka", autonym: "Maninkakan", isoCode: "emk", regionGroup: "West Africa and the Sahel", primaryRegion: "Guinea and Mali", tier: "EXPERIMENTAL_VERIFY" },
  { id: "susu", englishName: "Susu", autonym: "Sosoxui", isoCode: "sus", regionGroup: "West Africa and the Sahel", primaryRegion: "Guinea and Sierra Leone", tier: "EXPERIMENTAL_VERIFY" },
  { id: "krio", englishName: "Krio", autonym: "Krio", isoCode: "kri", regionGroup: "West Africa and the Sahel", primaryRegion: "Sierra Leone", tier: "GOOD_PRACTICAL" },
  { id: "temne", englishName: "Temne", autonym: "Themnɛ", isoCode: "tem", regionGroup: "West Africa and the Sahel", primaryRegion: "Sierra Leone", tier: "EXPERIMENTAL_VERIFY" },
  { id: "mende", englishName: "Mende", autonym: "Mende yia", isoCode: "men", regionGroup: "West Africa and the Sahel", primaryRegion: "Sierra Leone and Liberia", tier: "EXPERIMENTAL_VERIFY" },
  { id: "vai", englishName: "Vai", autonym: "Vai", isoCode: "vai", regionGroup: "West Africa and the Sahel", primaryRegion: "Liberia and Sierra Leone", tier: "EXPERIMENTAL_VERIFY" },
  { id: "kpelle", englishName: "Kpelle", autonym: "Kpelle", isoCode: "kpe", regionGroup: "West Africa and the Sahel", primaryRegion: "Liberia and Guinea", tier: "EXPERIMENTAL_VERIFY" },
  { id: "bassa", englishName: "Bassa", autonym: "Bassa", isoCode: "bsq", regionGroup: "West Africa and the Sahel", primaryRegion: "Liberia", tier: "EXPERIMENTAL_VERIFY" },
  { id: "fon", englishName: "Fon", autonym: "Fon gbe", isoCode: "fon", regionGroup: "West Africa and the Sahel", primaryRegion: "Benin and Togo", tier: "EXPERIMENTAL_VERIFY" },
  { id: "gun", englishName: "Gun", autonym: "Gungbe", isoCode: "guw", regionGroup: "West Africa and the Sahel", primaryRegion: "Benin and Nigeria", tier: "EXPERIMENTAL_VERIFY" },
  { id: "bariba", englishName: "Bariba", autonym: "Baatonum", isoCode: "bba", regionGroup: "West Africa and the Sahel", primaryRegion: "Benin and Nigeria", tier: "EXPERIMENTAL_VERIFY" },
  { id: "zarma", englishName: "Zarma", autonym: "Zarmaciine", isoCode: "dje", regionGroup: "West Africa and the Sahel", primaryRegion: "Niger", tier: "EXPERIMENTAL_VERIFY" },
  { id: "songhay-koyraboro-senni", englishName: "Songhay Koyraboro Senni", autonym: "Koyraboro Senni", isoCode: "ses", regionGroup: "West Africa and the Sahel", primaryRegion: "Mali", tier: "EXPERIMENTAL_VERIFY" },
  { id: "kanuri", englishName: "Kanuri", autonym: "Kanuri", isoCode: "kr", regionGroup: "West Africa and the Sahel", primaryRegion: "Nigeria, Niger and Chad", tier: "EXPERIMENTAL_VERIFY" },
  { id: "edo", englishName: "Edo", autonym: "Edo", isoCode: "bin", regionGroup: "West Africa and the Sahel", primaryRegion: "Nigeria", tier: "EXPERIMENTAL_VERIFY" },
  { id: "ibibio", englishName: "Ibibio", autonym: "Ibibio", isoCode: "ibb", regionGroup: "West Africa and the Sahel", primaryRegion: "Nigeria", tier: "EXPERIMENTAL_VERIFY" },
  { id: "efik", englishName: "Efik", autonym: "Efik", isoCode: "efi", regionGroup: "West Africa and the Sahel", primaryRegion: "Nigeria", tier: "EXPERIMENTAL_VERIFY" },
  { id: "ijaw", englishName: "Ijaw", autonym: "Izon", isoCode: "ijc", regionGroup: "West Africa and the Sahel", primaryRegion: "Nigeria", tier: "EXPERIMENTAL_VERIFY" },
  { id: "tiv", englishName: "Tiv", autonym: "Tiv", isoCode: "tiv", regionGroup: "West Africa and the Sahel", primaryRegion: "Nigeria", tier: "EXPERIMENTAL_VERIFY" },
  { id: "nupe", englishName: "Nupe", autonym: "Nupe", isoCode: "nup", regionGroup: "West Africa and the Sahel", primaryRegion: "Nigeria", tier: "EXPERIMENTAL_VERIFY" },
  { id: "gbagyi", englishName: "Gbagyi", autonym: "Gbagyi", isoCode: "gbr", regionGroup: "West Africa and the Sahel", primaryRegion: "Nigeria", tier: "EXPERIMENTAL_VERIFY" },
  { id: "idoma", englishName: "Idoma", autonym: "Idoma", isoCode: "idu", regionGroup: "West Africa and the Sahel", primaryRegion: "Nigeria", tier: "EXPERIMENTAL_VERIFY" },
  { id: "hassaniya-arabic", englishName: "Hassaniya Arabic", autonym: "Hassaniyya", isoCode: "mey", regionGroup: "West Africa and the Sahel", primaryRegion: "Mauritania and Western Sahara", tier: "EXPERIMENTAL_VERIFY" },
  { id: "cape-verdean-creole", englishName: "Cape Verdean Creole", autonym: "Kriolu", isoCode: "kea", regionGroup: "West Africa and the Sahel", primaryRegion: "Cabo Verde", tier: "GOOD_PRACTICAL" },
  { id: "guinea-bissau-creole", englishName: "Guinea Bissau Creole", autonym: "Kriol", isoCode: "pov", regionGroup: "West Africa and the Sahel", primaryRegion: "Guinea-Bissau", tier: "EXPERIMENTAL_VERIFY" },
  { id: "french", englishName: "French", autonym: "Francais", isoCode: "fr", regionGroup: "Central and Southern Africa", primaryRegion: "Central and West Africa; worldwide", tier: "STRONG" },
  { id: "portuguese", englishName: "Portuguese", autonym: "Portugues", isoCode: "pt", regionGroup: "Central and Southern Africa", primaryRegion: "Southern Africa; worldwide", tier: "STRONG" },
  { id: "afrikaans", englishName: "Afrikaans", autonym: "Afrikaans", isoCode: "af", regionGroup: "Central and Southern Africa", primaryRegion: "Southern Africa", tier: "STRONG" },
  { id: "zulu", englishName: "Zulu", autonym: "isiZulu", isoCode: "zu", regionGroup: "Central and Southern Africa", primaryRegion: "South Africa", tier: "GOOD_PRACTICAL" },
  { id: "xhosa", englishName: "Xhosa", autonym: "isiXhosa", isoCode: "xh", regionGroup: "Central and Southern Africa", primaryRegion: "South Africa", tier: "GOOD_PRACTICAL" },
  { id: "southern-sotho", englishName: "Southern Sotho", autonym: "Sesotho", isoCode: "st", regionGroup: "Central and Southern Africa", primaryRegion: "Lesotho and South Africa", tier: "GOOD_PRACTICAL" },
  { id: "northern-sotho", englishName: "Northern Sotho", autonym: "Sesotho sa Leboa", isoCode: "nso", regionGroup: "Central and Southern Africa", primaryRegion: "South Africa", tier: "GOOD_PRACTICAL" },
  { id: "tswana", englishName: "Tswana", autonym: "Setswana", isoCode: "tn", regionGroup: "Central and Southern Africa", primaryRegion: "Botswana and South Africa", tier: "GOOD_PRACTICAL" },
  { id: "tsonga", englishName: "Tsonga", autonym: "Xitsonga", isoCode: "ts", regionGroup: "Central and Southern Africa", primaryRegion: "South Africa and Mozambique", tier: "GOOD_PRACTICAL" },
  { id: "swati", englishName: "Swati", autonym: "siSwati", isoCode: "ss", regionGroup: "Central and Southern Africa", primaryRegion: "Eswatini and South Africa", tier: "GOOD_PRACTICAL" },
  { id: "venda", englishName: "Venda", autonym: "Tshivenda", isoCode: "ve", regionGroup: "Central and Southern Africa", primaryRegion: "South Africa and Zimbabwe", tier: "EXPERIMENTAL_VERIFY" },
  { id: "ndebele", englishName: "Ndebele", autonym: "isiNdebele", isoCode: "nr", regionGroup: "Central and Southern Africa", primaryRegion: "South Africa and Zimbabwe", tier: "EXPERIMENTAL_VERIFY" },
  { id: "shona", englishName: "Shona", autonym: "chiShona", isoCode: "sn", regionGroup: "Central and Southern Africa", primaryRegion: "Zimbabwe", tier: "GOOD_PRACTICAL" },
  { id: "chichewa", englishName: "Chichewa", autonym: "Chichewa", isoCode: "ny", regionGroup: "Central and Southern Africa", primaryRegion: "Malawi, Zambia and Mozambique", tier: "GOOD_PRACTICAL" },
  { id: "bemba", englishName: "Bemba", autonym: "Ichibemba", isoCode: "bem", regionGroup: "Central and Southern Africa", primaryRegion: "Zambia and DR Congo", tier: "GOOD_PRACTICAL" },
  { id: "tonga-zambia", englishName: "Tonga Zambia", autonym: "Chitonga", isoCode: "toi", regionGroup: "Central and Southern Africa", primaryRegion: "Zambia and Zimbabwe", tier: "EXPERIMENTAL_VERIFY" },
  { id: "lozi", englishName: "Lozi", autonym: "Silozi", isoCode: "loz", regionGroup: "Central and Southern Africa", primaryRegion: "Zambia and neighboring states", tier: "EXPERIMENTAL_VERIFY" },
  { id: "lunda", englishName: "Lunda", autonym: "Chilunda", isoCode: "lun", regionGroup: "Central and Southern Africa", primaryRegion: "Zambia, Angola and DR Congo", tier: "EXPERIMENTAL_VERIFY" },
  { id: "luvale", englishName: "Luvale", autonym: "Chiluvale", isoCode: "lue", regionGroup: "Central and Southern Africa", primaryRegion: "Zambia and Angola", tier: "EXPERIMENTAL_VERIFY" },
  { id: "nyaneka", englishName: "Nyaneka", autonym: "Olunyaneka", isoCode: "nyk", regionGroup: "Central and Southern Africa", primaryRegion: "Angola", tier: "EXPERIMENTAL_VERIFY" },
  { id: "umbundu", englishName: "Umbundu", autonym: "Umbundu", isoCode: "umb", regionGroup: "Central and Southern Africa", primaryRegion: "Angola", tier: "EXPERIMENTAL_VERIFY" },
  { id: "kimbundu", englishName: "Kimbundu", autonym: "Kimbundu", isoCode: "kmb", regionGroup: "Central and Southern Africa", primaryRegion: "Angola", tier: "EXPERIMENTAL_VERIFY" },
  { id: "kikongo", englishName: "Kikongo", autonym: "Kikongo", isoCode: "kg", regionGroup: "Central and Southern Africa", primaryRegion: "Angola and Congo basin", tier: "EXPERIMENTAL_VERIFY" },
  { id: "kituba", englishName: "Kituba", autonym: "Kikongo ya Leta", isoCode: "ktu", regionGroup: "Central and Southern Africa", primaryRegion: "DR Congo and Republic of the Congo", tier: "EXPERIMENTAL_VERIFY" },
  { id: "tshiluba", englishName: "Tshiluba", autonym: "Tshiluba", isoCode: "lua", regionGroup: "Central and Southern Africa", primaryRegion: "DR Congo", tier: "GOOD_PRACTICAL" },
  { id: "luba-katanga", englishName: "Luba Katanga", autonym: "Kiluba", isoCode: "lu", regionGroup: "Central and Southern Africa", primaryRegion: "DR Congo", tier: "EXPERIMENTAL_VERIFY" },
  { id: "mongo", englishName: "Mongo", autonym: "Lomongo", isoCode: "lol", regionGroup: "Central and Southern Africa", primaryRegion: "DR Congo", tier: "EXPERIMENTAL_VERIFY" },
  { id: "sango", englishName: "Sango", autonym: "Sango", isoCode: "sg", regionGroup: "Central and Southern Africa", primaryRegion: "Central African Republic", tier: "GOOD_PRACTICAL" },
  { id: "fang", englishName: "Fang", autonym: "Fang", isoCode: "fan", regionGroup: "Central and Southern Africa", primaryRegion: "Equatorial Guinea, Gabon and Cameroon", tier: "EXPERIMENTAL_VERIFY" },
  { id: "duala", englishName: "Duala", autonym: "Duala", isoCode: "dua", regionGroup: "Central and Southern Africa", primaryRegion: "Cameroon", tier: "EXPERIMENTAL_VERIFY" },
  { id: "ewondo", englishName: "Ewondo", autonym: "Ewondo", isoCode: "ewo", regionGroup: "Central and Southern Africa", primaryRegion: "Cameroon", tier: "EXPERIMENTAL_VERIFY" },
  { id: "chokwe", englishName: "Chokwe", autonym: "Cokwe", isoCode: "cjk", regionGroup: "Central and Southern Africa", primaryRegion: "Angola, Zambia and DR Congo", tier: "EXPERIMENTAL_VERIFY" },
  { id: "herero", englishName: "Herero", autonym: "Otjiherero", isoCode: "hz", regionGroup: "Central and Southern Africa", primaryRegion: "Namibia and Botswana", tier: "EXPERIMENTAL_VERIFY" },
  { id: "ndonga", englishName: "Ndonga", autonym: "Oshindonga", isoCode: "ng", regionGroup: "Central and Southern Africa", primaryRegion: "Namibia and Angola", tier: "EXPERIMENTAL_VERIFY" },
  { id: "kwangali", englishName: "Kwangali", autonym: "Rukwangali", isoCode: "kwn", regionGroup: "Central and Southern Africa", primaryRegion: "Namibia and Angola", tier: "EXPERIMENTAL_VERIFY" },
  { id: "khoekhoegowab", englishName: "Khoekhoegowab", autonym: "Khoekhoegowab", isoCode: "naq", regionGroup: "Central and Southern Africa", primaryRegion: "Namibia and Botswana", tier: "EXPERIMENTAL_VERIFY" },
  { id: "setswana-kalanga", englishName: "Setswana Kalanga", autonym: "Ikalanga", isoCode: "kck", regionGroup: "Central and Southern Africa", primaryRegion: "Botswana and Zimbabwe", tier: "EXPERIMENTAL_VERIFY" },
  { id: "makhuwa", englishName: "Makhuwa", autonym: "Emakhuwa", isoCode: "vmw", regionGroup: "Central and Southern Africa", primaryRegion: "Mozambique", tier: "EXPERIMENTAL_VERIFY" },
  { id: "sena", englishName: "Sena", autonym: "Cisena", isoCode: "seh", regionGroup: "Central and Southern Africa", primaryRegion: "Mozambique and Malawi", tier: "EXPERIMENTAL_VERIFY" },
  { id: "arabic", englishName: "Arabic", autonym: "العربية", isoCode: "ar", regionGroup: "North Africa and the Middle East", primaryRegion: "Middle East and North Africa", tier: "STRONG" },
  { id: "egyptian-arabic", englishName: "Egyptian Arabic", autonym: "مصري", isoCode: "arz", regionGroup: "North Africa and the Middle East", primaryRegion: "Egypt", tier: "GOOD_PRACTICAL" },
  { id: "moroccan-arabic", englishName: "Moroccan Arabic", autonym: "الدارجة المغربية", isoCode: "ary", regionGroup: "North Africa and the Middle East", primaryRegion: "Morocco", tier: "GOOD_PRACTICAL" },
  { id: "algerian-arabic", englishName: "Algerian Arabic", autonym: "الدارجة الجزائرية", isoCode: "arq", regionGroup: "North Africa and the Middle East", primaryRegion: "Algeria", tier: "GOOD_PRACTICAL" },
  { id: "tunisian-arabic", englishName: "Tunisian Arabic", autonym: "تونسي", isoCode: "aeb", regionGroup: "North Africa and the Middle East", primaryRegion: "Tunisia", tier: "GOOD_PRACTICAL" },
  { id: "levantine-arabic", englishName: "Levantine Arabic", autonym: "شامي", isoCode: "apc", regionGroup: "North Africa and the Middle East", primaryRegion: "Levant", tier: "GOOD_PRACTICAL" },
  { id: "gulf-arabic", englishName: "Gulf Arabic", autonym: "خليجي", isoCode: "afb", regionGroup: "North Africa and the Middle East", primaryRegion: "Arabian Gulf", tier: "GOOD_PRACTICAL" },
  { id: "hebrew", englishName: "Hebrew", autonym: "עברית", isoCode: "he", regionGroup: "North Africa and the Middle East", primaryRegion: "Israel and worldwide", tier: "STRONG" },
  { id: "persian", englishName: "Persian", autonym: "فارسی", isoCode: "fa", regionGroup: "North Africa and the Middle East", primaryRegion: "Iran and diaspora", tier: "STRONG" },
  { id: "dari", englishName: "Dari", autonym: "دری", isoCode: "prs", regionGroup: "North Africa and the Middle East", primaryRegion: "Afghanistan", tier: "GOOD_PRACTICAL" },
  { id: "kurdish-kurmanji", englishName: "Kurdish Kurmanji", autonym: "Kurmancî", isoCode: "ku", regionGroup: "North Africa and the Middle East", primaryRegion: "Turkey, Syria and diaspora", tier: "GOOD_PRACTICAL" },
  { id: "kurdish-sorani", englishName: "Kurdish Sorani", autonym: "کوردیی ناوەندی", isoCode: "ckb", regionGroup: "North Africa and the Middle East", primaryRegion: "Iraq and Iran", tier: "GOOD_PRACTICAL" },
  { id: "turkish", englishName: "Turkish", autonym: "Türkçe", isoCode: "tr", regionGroup: "North Africa and the Middle East", primaryRegion: "Turkey and diaspora", tier: "STRONG" },
  { id: "azerbaijani", englishName: "Azerbaijani", autonym: "Azərbaycan dili", isoCode: "az", regionGroup: "North Africa and the Middle East", primaryRegion: "Azerbaijan and Iran", tier: "STRONG" },
  { id: "armenian", englishName: "Armenian", autonym: "Հայերեն", isoCode: "hy", regionGroup: "North Africa and the Middle East", primaryRegion: "Armenia and diaspora", tier: "GOOD_PRACTICAL" },
  { id: "georgian", englishName: "Georgian", autonym: "ქართული", isoCode: "ka", regionGroup: "North Africa and the Middle East", primaryRegion: "Georgia", tier: "GOOD_PRACTICAL" },
  { id: "assyrian-neo-aramaic", englishName: "Assyrian Neo-Aramaic", autonym: "Suryaya", isoCode: "aii", regionGroup: "North Africa and the Middle East", primaryRegion: "Iraq and diaspora", tier: "EXPERIMENTAL_VERIFY" },
  { id: "western-neo-aramaic", englishName: "Western Neo-Aramaic", autonym: "Lishana Aramaya", isoCode: "amw", regionGroup: "North Africa and the Middle East", primaryRegion: "Syria", tier: "EXPERIMENTAL_VERIFY" },
  { id: "kabyle", englishName: "Kabyle", autonym: "Taqbaylit", isoCode: "kab", regionGroup: "North Africa and the Middle East", primaryRegion: "Algeria", tier: "GOOD_PRACTICAL" },
  { id: "central-atlas-tamazight", englishName: "Central Atlas Tamazight", autonym: "Tamazight", isoCode: "tzm", regionGroup: "North Africa and the Middle East", primaryRegion: "Morocco", tier: "EXPERIMENTAL_VERIFY" },
  { id: "tachelhit", englishName: "Tachelhit", autonym: "Taclḥit", isoCode: "shi", regionGroup: "North Africa and the Middle East", primaryRegion: "Morocco", tier: "EXPERIMENTAL_VERIFY" },
  { id: "tamazight", englishName: "Tamazight", autonym: "Tamaziɣt", isoCode: "zgh", regionGroup: "North Africa and the Middle East", primaryRegion: "North Africa", tier: "GOOD_PRACTICAL" },
  { id: "tamasheq", englishName: "Tamasheq", autonym: "Tamasheq", isoCode: "taq", regionGroup: "North Africa and the Middle East", primaryRegion: "Mali and Niger", tier: "EXPERIMENTAL_VERIFY" },
  { id: "tuareg-tawallammat", englishName: "Tuareg Tawallammat", autonym: "Tawallammat Tamajaq", isoCode: "ttq", regionGroup: "North Africa and the Middle East", primaryRegion: "Niger and Mali", tier: "EXPERIMENTAL_VERIFY" },
  { id: "coptic", englishName: "Coptic", autonym: "Metremenkimi", isoCode: "cop", regionGroup: "North Africa and the Middle East", primaryRegion: "Egypt liturgical", tier: "EXPERIMENTAL_VERIFY" },
  { id: "english", englishName: "English", autonym: "English", isoCode: "en", regionGroup: "Europe and the Caucasus", primaryRegion: "Worldwide", tier: "STRONG" },
  { id: "spanish", englishName: "Spanish", autonym: "Español", isoCode: "es", regionGroup: "Europe and the Caucasus", primaryRegion: "Europe and the Americas", tier: "STRONG" },
  { id: "german", englishName: "German", autonym: "Deutsch", isoCode: "de", regionGroup: "Europe and the Caucasus", primaryRegion: "Central Europe", tier: "STRONG" },
  { id: "italian", englishName: "Italian", autonym: "Italiano", isoCode: "it", regionGroup: "Europe and the Caucasus", primaryRegion: "Southern Europe", tier: "STRONG" },
  { id: "dutch", englishName: "Dutch", autonym: "Nederlands", isoCode: "nl", regionGroup: "Europe and the Caucasus", primaryRegion: "Western Europe", tier: "STRONG" },
  { id: "russian", englishName: "Russian", autonym: "Русский", isoCode: "ru", regionGroup: "Europe and the Caucasus", primaryRegion: "Eastern Europe and Eurasia", tier: "STRONG" },
  { id: "ukrainian", englishName: "Ukrainian", autonym: "Українська", isoCode: "uk", regionGroup: "Europe and the Caucasus", primaryRegion: "Ukraine and diaspora", tier: "STRONG" },
  { id: "polish", englishName: "Polish", autonym: "Polski", isoCode: "pl", regionGroup: "Europe and the Caucasus", primaryRegion: "Poland and diaspora", tier: "STRONG" },
  { id: "romanian", englishName: "Romanian", autonym: "Română", isoCode: "ro", regionGroup: "Europe and the Caucasus", primaryRegion: "Romania and Moldova", tier: "STRONG" },
  { id: "greek", englishName: "Greek", autonym: "Ελληνικά", isoCode: "el", regionGroup: "Europe and the Caucasus", primaryRegion: "Greece and Cyprus", tier: "STRONG" },
  { id: "swedish", englishName: "Swedish", autonym: "Svenska", isoCode: "sv", regionGroup: "Europe and the Caucasus", primaryRegion: "Sweden and Finland", tier: "STRONG" },
  { id: "norwegian-bokmal", englishName: "Norwegian Bokmal", autonym: "Norsk bokmål", isoCode: "nb", regionGroup: "Europe and the Caucasus", primaryRegion: "Norway", tier: "STRONG" },
  { id: "norwegian-nynorsk", englishName: "Norwegian Nynorsk", autonym: "Norsk nynorsk", isoCode: "nn", regionGroup: "Europe and the Caucasus", primaryRegion: "Norway", tier: "GOOD_PRACTICAL" },
  { id: "danish", englishName: "Danish", autonym: "Dansk", isoCode: "da", regionGroup: "Europe and the Caucasus", primaryRegion: "Denmark", tier: "STRONG" },
  { id: "finnish", englishName: "Finnish", autonym: "Suomi", isoCode: "fi", regionGroup: "Europe and the Caucasus", primaryRegion: "Finland", tier: "STRONG" },
  { id: "icelandic", englishName: "Icelandic", autonym: "Íslenska", isoCode: "is", regionGroup: "Europe and the Caucasus", primaryRegion: "Iceland", tier: "GOOD_PRACTICAL" },
  { id: "irish", englishName: "Irish", autonym: "Gaeilge", isoCode: "ga", regionGroup: "Europe and the Caucasus", primaryRegion: "Ireland", tier: "GOOD_PRACTICAL" },
  { id: "scottish-gaelic", englishName: "Scottish Gaelic", autonym: "Gàidhlig", isoCode: "gd", regionGroup: "Europe and the Caucasus", primaryRegion: "Scotland", tier: "GOOD_PRACTICAL" },
  { id: "welsh", englishName: "Welsh", autonym: "Cymraeg", isoCode: "cy", regionGroup: "Europe and the Caucasus", primaryRegion: "Wales", tier: "GOOD_PRACTICAL" },
  { id: "breton", englishName: "Breton", autonym: "Brezhoneg", isoCode: "br", regionGroup: "Europe and the Caucasus", primaryRegion: "France", tier: "EXPERIMENTAL_VERIFY" },
  { id: "basque", englishName: "Basque", autonym: "Euskara", isoCode: "eu", regionGroup: "Europe and the Caucasus", primaryRegion: "Spain and France", tier: "GOOD_PRACTICAL" },
  { id: "catalan", englishName: "Catalan", autonym: "Català", isoCode: "ca", regionGroup: "Europe and the Caucasus", primaryRegion: "Spain, Andorra and France", tier: "STRONG" },
  { id: "galician", englishName: "Galician", autonym: "Galego", isoCode: "gl", regionGroup: "Europe and the Caucasus", primaryRegion: "Spain", tier: "GOOD_PRACTICAL" },
  { id: "occitan", englishName: "Occitan", autonym: "Occitan", isoCode: "oc", regionGroup: "Europe and the Caucasus", primaryRegion: "France, Spain and Italy", tier: "EXPERIMENTAL_VERIFY" },
  { id: "corsican", englishName: "Corsican", autonym: "Corsu", isoCode: "co", regionGroup: "Europe and the Caucasus", primaryRegion: "Corsica", tier: "EXPERIMENTAL_VERIFY" },
  { id: "maltese", englishName: "Maltese", autonym: "Malti", isoCode: "mt", regionGroup: "Europe and the Caucasus", primaryRegion: "Malta", tier: "GOOD_PRACTICAL" },
  { id: "albanian", englishName: "Albanian", autonym: "Shqip", isoCode: "sq", regionGroup: "Europe and the Caucasus", primaryRegion: "Albania and Balkans", tier: "GOOD_PRACTICAL" },
  { id: "bosnian", englishName: "Bosnian", autonym: "Bosanski", isoCode: "bs", regionGroup: "Europe and the Caucasus", primaryRegion: "Bosnia and Herzegovina", tier: "GOOD_PRACTICAL" },
  { id: "croatian", englishName: "Croatian", autonym: "Hrvatski", isoCode: "hr", regionGroup: "Europe and the Caucasus", primaryRegion: "Croatia", tier: "STRONG" },
  { id: "serbian", englishName: "Serbian", autonym: "Српски", isoCode: "sr", regionGroup: "Europe and the Caucasus", primaryRegion: "Serbia and Balkans", tier: "STRONG" },
  { id: "slovenian", englishName: "Slovenian", autonym: "Slovenščina", isoCode: "sl", regionGroup: "Europe and the Caucasus", primaryRegion: "Slovenia", tier: "GOOD_PRACTICAL" },
  { id: "macedonian", englishName: "Macedonian", autonym: "Македонски", isoCode: "mk", regionGroup: "Europe and the Caucasus", primaryRegion: "North Macedonia", tier: "GOOD_PRACTICAL" },
  { id: "bulgarian", englishName: "Bulgarian", autonym: "Български", isoCode: "bg", regionGroup: "Europe and the Caucasus", primaryRegion: "Bulgaria", tier: "STRONG" },
  { id: "czech", englishName: "Czech", autonym: "Čeština", isoCode: "cs", regionGroup: "Europe and the Caucasus", primaryRegion: "Czechia", tier: "STRONG" },
  { id: "slovak", englishName: "Slovak", autonym: "Slovenčina", isoCode: "sk", regionGroup: "Europe and the Caucasus", primaryRegion: "Slovakia", tier: "GOOD_PRACTICAL" },
  { id: "hungarian", englishName: "Hungarian", autonym: "Magyar", isoCode: "hu", regionGroup: "Europe and the Caucasus", primaryRegion: "Hungary and neighboring states", tier: "STRONG" },
  { id: "estonian", englishName: "Estonian", autonym: "Eesti", isoCode: "et", regionGroup: "Europe and the Caucasus", primaryRegion: "Estonia", tier: "GOOD_PRACTICAL" },
  { id: "latvian", englishName: "Latvian", autonym: "Latviešu", isoCode: "lv", regionGroup: "Europe and the Caucasus", primaryRegion: "Latvia", tier: "GOOD_PRACTICAL" },
  { id: "lithuanian", englishName: "Lithuanian", autonym: "Lietuvių", isoCode: "lt", regionGroup: "Europe and the Caucasus", primaryRegion: "Lithuania", tier: "GOOD_PRACTICAL" },
  { id: "belarusian", englishName: "Belarusian", autonym: "Беларуская", isoCode: "be", regionGroup: "Europe and the Caucasus", primaryRegion: "Belarus", tier: "GOOD_PRACTICAL" },
  { id: "moldovan", englishName: "Moldovan", autonym: "Română", isoCode: "ro", regionGroup: "Europe and the Caucasus", primaryRegion: "Moldova", tier: "GOOD_PRACTICAL" },
  { id: "luxembourgish", englishName: "Luxembourgish", autonym: "Lëtzebuergesch", isoCode: "lb", regionGroup: "Europe and the Caucasus", primaryRegion: "Luxembourg", tier: "GOOD_PRACTICAL" },
  { id: "frisian", englishName: "Frisian", autonym: "Frysk", isoCode: "fy", regionGroup: "Europe and the Caucasus", primaryRegion: "Netherlands and Germany", tier: "EXPERIMENTAL_VERIFY" },
  { id: "faroese", englishName: "Faroese", autonym: "Føroyskt", isoCode: "fo", regionGroup: "Europe and the Caucasus", primaryRegion: "Faroe Islands", tier: "GOOD_PRACTICAL" },
  { id: "romansh", englishName: "Romansh", autonym: "Rumantsch", isoCode: "rm", regionGroup: "Europe and the Caucasus", primaryRegion: "Switzerland", tier: "EXPERIMENTAL_VERIFY" },
  { id: "sardinian", englishName: "Sardinian", autonym: "Sardu", isoCode: "sc", regionGroup: "Europe and the Caucasus", primaryRegion: "Sardinia", tier: "EXPERIMENTAL_VERIFY" },
  { id: "sicilian", englishName: "Sicilian", autonym: "Sicilianu", isoCode: "scn", regionGroup: "Europe and the Caucasus", primaryRegion: "Italy", tier: "EXPERIMENTAL_VERIFY" },
  { id: "neapolitan", englishName: "Neapolitan", autonym: "Napulitano", isoCode: "nap", regionGroup: "Europe and the Caucasus", primaryRegion: "Italy", tier: "EXPERIMENTAL_VERIFY" },
  { id: "yiddish", englishName: "Yiddish", autonym: "ייִדיש", isoCode: "yi", regionGroup: "Europe and the Caucasus", primaryRegion: "Europe and worldwide diaspora", tier: "GOOD_PRACTICAL" },
  { id: "romani", englishName: "Romani", autonym: "Romani chib", isoCode: "rom", regionGroup: "Europe and the Caucasus", primaryRegion: "Europe and diaspora", tier: "EXPERIMENTAL_VERIFY" },
  { id: "manx", englishName: "Manx", autonym: "Gaelg", isoCode: "gv", regionGroup: "Europe and the Caucasus", primaryRegion: "Isle of Man", tier: "EXPERIMENTAL_VERIFY" },
  { id: "cornish", englishName: "Cornish", autonym: "Kernewek", isoCode: "kw", regionGroup: "Europe and the Caucasus", primaryRegion: "Cornwall", tier: "EXPERIMENTAL_VERIFY" },
  { id: "sami-northern", englishName: "Sami Northern", autonym: "Davvisámegiella", isoCode: "se", regionGroup: "Europe and the Caucasus", primaryRegion: "Northern Europe", tier: "GOOD_PRACTICAL" },
  { id: "sami-inari", englishName: "Sami Inari", autonym: "Anarâškielâ", isoCode: "smn", regionGroup: "Europe and the Caucasus", primaryRegion: "Finland", tier: "EXPERIMENTAL_VERIFY" },
  { id: "sami-skolt", englishName: "Sami Skolt", autonym: "Sääʹmǩiõll", isoCode: "sms", regionGroup: "Europe and the Caucasus", primaryRegion: "Finland and Russia", tier: "EXPERIMENTAL_VERIFY" },
  { id: "hindi", englishName: "Hindi", autonym: "हिन्दी", isoCode: "hi", regionGroup: "South and Central Asia", primaryRegion: "India and diaspora", tier: "STRONG" },
  { id: "urdu", englishName: "Urdu", autonym: "اردو", isoCode: "ur", regionGroup: "South and Central Asia", primaryRegion: "Pakistan, India and diaspora", tier: "STRONG" },
  { id: "bengali", englishName: "Bengali", autonym: "বাংলা", isoCode: "bn", regionGroup: "South and Central Asia", primaryRegion: "Bangladesh, India and diaspora", tier: "STRONG" },
  { id: "punjabi", englishName: "Punjabi", autonym: "ਪੰਜਾਬੀ", isoCode: "pa", regionGroup: "South and Central Asia", primaryRegion: "India, Pakistan and diaspora", tier: "STRONG" },
  { id: "gujarati", englishName: "Gujarati", autonym: "ગુજરાતી", isoCode: "gu", regionGroup: "South and Central Asia", primaryRegion: "India and diaspora", tier: "STRONG" },
  { id: "marathi", englishName: "Marathi", autonym: "मराठी", isoCode: "mr", regionGroup: "South and Central Asia", primaryRegion: "India", tier: "STRONG" },
  { id: "nepali", englishName: "Nepali", autonym: "नेपाली", isoCode: "ne", regionGroup: "South and Central Asia", primaryRegion: "Nepal and India", tier: "GOOD_PRACTICAL" },
  { id: "sinhala", englishName: "Sinhala", autonym: "සිංහල", isoCode: "si", regionGroup: "South and Central Asia", primaryRegion: "Sri Lanka", tier: "GOOD_PRACTICAL" },
  { id: "tamil", englishName: "Tamil", autonym: "தமிழ்", isoCode: "ta", regionGroup: "South and Central Asia", primaryRegion: "India, Sri Lanka and diaspora", tier: "STRONG" },
  { id: "telugu", englishName: "Telugu", autonym: "తెలుగు", isoCode: "te", regionGroup: "South and Central Asia", primaryRegion: "India and diaspora", tier: "STRONG" },
  { id: "kannada", englishName: "Kannada", autonym: "ಕನ್ನಡ", isoCode: "kn", regionGroup: "South and Central Asia", primaryRegion: "India", tier: "STRONG" },
  { id: "malayalam", englishName: "Malayalam", autonym: "മലയാളം", isoCode: "ml", regionGroup: "South and Central Asia", primaryRegion: "India and diaspora", tier: "STRONG" },
  { id: "odia", englishName: "Odia", autonym: "ଓଡ଼ିଆ", isoCode: "or", regionGroup: "South and Central Asia", primaryRegion: "India", tier: "GOOD_PRACTICAL" },
  { id: "assamese", englishName: "Assamese", autonym: "অসমীয়া", isoCode: "as", regionGroup: "South and Central Asia", primaryRegion: "India", tier: "GOOD_PRACTICAL" },
  { id: "kashmiri", englishName: "Kashmiri", autonym: "کٲشُر", isoCode: "ks", regionGroup: "South and Central Asia", primaryRegion: "India and Pakistan", tier: "EXPERIMENTAL_VERIFY" },
  { id: "sindhi", englishName: "Sindhi", autonym: "سنڌي", isoCode: "sd", regionGroup: "South and Central Asia", primaryRegion: "Pakistan and India", tier: "GOOD_PRACTICAL" },
  { id: "pashto", englishName: "Pashto", autonym: "پښتو", isoCode: "ps", regionGroup: "South and Central Asia", primaryRegion: "Afghanistan and Pakistan", tier: "GOOD_PRACTICAL" },
  { id: "baluchi", englishName: "Baluchi", autonym: "بلوچی", isoCode: "bal", regionGroup: "South and Central Asia", primaryRegion: "Pakistan, Iran and Afghanistan", tier: "EXPERIMENTAL_VERIFY" },
  { id: "brahui", englishName: "Brahui", autonym: "براوی", isoCode: "brh", regionGroup: "South and Central Asia", primaryRegion: "Pakistan and Afghanistan", tier: "EXPERIMENTAL_VERIFY" },
  { id: "dzongkha", englishName: "Dzongkha", autonym: "རྫོང་ཁ", isoCode: "dz", regionGroup: "South and Central Asia", primaryRegion: "Bhutan", tier: "GOOD_PRACTICAL" },
  { id: "tibetan", englishName: "Tibetan", autonym: "བོད་ཡིག", isoCode: "bo", regionGroup: "South and Central Asia", primaryRegion: "Tibet and Himalayas", tier: "GOOD_PRACTICAL" },
  { id: "meitei", englishName: "Meitei", autonym: "মৈতৈলোন্", isoCode: "mni", regionGroup: "South and Central Asia", primaryRegion: "Northeast India", tier: "EXPERIMENTAL_VERIFY" },
  { id: "mizo", englishName: "Mizo", autonym: "Mizo tawng", isoCode: "lus", regionGroup: "South and Central Asia", primaryRegion: "Northeast India", tier: "EXPERIMENTAL_VERIFY" },
  { id: "khasi", englishName: "Khasi", autonym: "Ka Ktien Khasi", isoCode: "kha", regionGroup: "South and Central Asia", primaryRegion: "Northeast India", tier: "EXPERIMENTAL_VERIFY" },
  { id: "santali", englishName: "Santali", autonym: "ᱥᱟᱱᱛᱟᱲᱤ", isoCode: "sat", regionGroup: "South and Central Asia", primaryRegion: "India, Bangladesh and Nepal", tier: "EXPERIMENTAL_VERIFY" },
  { id: "bhojpuri", englishName: "Bhojpuri", autonym: "भोजपुरी", isoCode: "bho", regionGroup: "South and Central Asia", primaryRegion: "India, Nepal and diaspora", tier: "GOOD_PRACTICAL" },
  { id: "maithili", englishName: "Maithili", autonym: "मैथिली", isoCode: "mai", regionGroup: "South and Central Asia", primaryRegion: "India and Nepal", tier: "GOOD_PRACTICAL" },
  { id: "awadhi", englishName: "Awadhi", autonym: "अवधी", isoCode: "awa", regionGroup: "South and Central Asia", primaryRegion: "India and Nepal", tier: "EXPERIMENTAL_VERIFY" },
  { id: "chhattisgarhi", englishName: "Chhattisgarhi", autonym: "छत्तीसगढ़ी", isoCode: "hne", regionGroup: "South and Central Asia", primaryRegion: "India", tier: "EXPERIMENTAL_VERIFY" },
  { id: "dogri", englishName: "Dogri", autonym: "डोगरी", isoCode: "doi", regionGroup: "South and Central Asia", primaryRegion: "India", tier: "EXPERIMENTAL_VERIFY" },
  { id: "konkani", englishName: "Konkani", autonym: "कोंकणी", isoCode: "kok", regionGroup: "South and Central Asia", primaryRegion: "India", tier: "GOOD_PRACTICAL" },
  { id: "kazakh", englishName: "Kazakh", autonym: "Қазақ тілі", isoCode: "kk", regionGroup: "South and Central Asia", primaryRegion: "Kazakhstan and Central Asia", tier: "GOOD_PRACTICAL" },
  { id: "kyrgyz", englishName: "Kyrgyz", autonym: "Кыргызча", isoCode: "ky", regionGroup: "South and Central Asia", primaryRegion: "Kyrgyzstan", tier: "GOOD_PRACTICAL" },
  { id: "uzbek", englishName: "Uzbek", autonym: "O'zbekcha", isoCode: "uz", regionGroup: "South and Central Asia", primaryRegion: "Uzbekistan and Central Asia", tier: "GOOD_PRACTICAL" },
  { id: "turkmen", englishName: "Turkmen", autonym: "Türkmençe", isoCode: "tk", regionGroup: "South and Central Asia", primaryRegion: "Turkmenistan", tier: "GOOD_PRACTICAL" },
  { id: "tajik", englishName: "Tajik", autonym: "Тоҷикӣ", isoCode: "tg", regionGroup: "South and Central Asia", primaryRegion: "Tajikistan", tier: "GOOD_PRACTICAL" },
  { id: "uyghur", englishName: "Uyghur", autonym: "ئۇيغۇرچە", isoCode: "ug", regionGroup: "South and Central Asia", primaryRegion: "China and Central Asia", tier: "GOOD_PRACTICAL" },
  { id: "mongolian", englishName: "Mongolian", autonym: "Монгол хэл", isoCode: "mn", regionGroup: "South and Central Asia", primaryRegion: "Mongolia and China", tier: "GOOD_PRACTICAL" },
  { id: "chinese-mandarin", englishName: "Chinese Mandarin", autonym: "中文", isoCode: "zh", regionGroup: "East and Southeast Asia", primaryRegion: "China, Taiwan and worldwide", tier: "STRONG" },
  { id: "cantonese", englishName: "Cantonese", autonym: "粵語", isoCode: "yue", regionGroup: "East and Southeast Asia", primaryRegion: "Hong Kong, southern China and diaspora", tier: "GOOD_PRACTICAL" },
  { id: "hokkien", englishName: "Hokkien", autonym: "福建話", isoCode: "nan", regionGroup: "East and Southeast Asia", primaryRegion: "China, Taiwan and Southeast Asia", tier: "EXPERIMENTAL_VERIFY" },
  { id: "hakka", englishName: "Hakka", autonym: "客家話", isoCode: "hak", regionGroup: "East and Southeast Asia", primaryRegion: "China, Taiwan and diaspora", tier: "EXPERIMENTAL_VERIFY" },
  { id: "wu-chinese", englishName: "Wu Chinese", autonym: "吴语", isoCode: "wuu", regionGroup: "East and Southeast Asia", primaryRegion: "Eastern China", tier: "EXPERIMENTAL_VERIFY" },
  { id: "japanese", englishName: "Japanese", autonym: "日本語", isoCode: "ja", regionGroup: "East and Southeast Asia", primaryRegion: "Japan and diaspora", tier: "STRONG" },
  { id: "korean", englishName: "Korean", autonym: "한국어", isoCode: "ko", regionGroup: "East and Southeast Asia", primaryRegion: "Korean Peninsula and diaspora", tier: "STRONG" },
  { id: "vietnamese", englishName: "Vietnamese", autonym: "Tiếng Việt", isoCode: "vi", regionGroup: "East and Southeast Asia", primaryRegion: "Vietnam and diaspora", tier: "STRONG" },
  { id: "thai", englishName: "Thai", autonym: "ภาษาไทย", isoCode: "th", regionGroup: "East and Southeast Asia", primaryRegion: "Thailand", tier: "STRONG" },
  { id: "lao", englishName: "Lao", autonym: "ພາສາລາວ", isoCode: "lo", regionGroup: "East and Southeast Asia", primaryRegion: "Laos", tier: "GOOD_PRACTICAL" },
  { id: "khmer", englishName: "Khmer", autonym: "ភាសាខ្មែរ", isoCode: "km", regionGroup: "East and Southeast Asia", primaryRegion: "Cambodia", tier: "GOOD_PRACTICAL" },
  { id: "burmese", englishName: "Burmese", autonym: "မြန်မာဘာသာ", isoCode: "my", regionGroup: "East and Southeast Asia", primaryRegion: "Myanmar", tier: "GOOD_PRACTICAL" },
  { id: "indonesian", englishName: "Indonesian", autonym: "Bahasa Indonesia", isoCode: "id", regionGroup: "East and Southeast Asia", primaryRegion: "Indonesia", tier: "STRONG" },
  { id: "malay", englishName: "Malay", autonym: "Bahasa Melayu", isoCode: "ms", regionGroup: "East and Southeast Asia", primaryRegion: "Malaysia, Brunei and Singapore", tier: "STRONG" },
  { id: "javanese", englishName: "Javanese", autonym: "Basa Jawa", isoCode: "jv", regionGroup: "East and Southeast Asia", primaryRegion: "Indonesia", tier: "GOOD_PRACTICAL" },
  { id: "sundanese", englishName: "Sundanese", autonym: "Basa Sunda", isoCode: "su", regionGroup: "East and Southeast Asia", primaryRegion: "Indonesia", tier: "GOOD_PRACTICAL" },
  { id: "balinese", englishName: "Balinese", autonym: "Basa Bali", isoCode: "ban", regionGroup: "East and Southeast Asia", primaryRegion: "Indonesia", tier: "EXPERIMENTAL_VERIFY" },
  { id: "madurese", englishName: "Madurese", autonym: "Basa Madhura", isoCode: "mad", regionGroup: "East and Southeast Asia", primaryRegion: "Indonesia", tier: "EXPERIMENTAL_VERIFY" },
  { id: "minangkabau", englishName: "Minangkabau", autonym: "Baso Minangkabau", isoCode: "min", regionGroup: "East and Southeast Asia", primaryRegion: "Indonesia", tier: "EXPERIMENTAL_VERIFY" },
  { id: "acehnese", englishName: "Acehnese", autonym: "Bahsa Acèh", isoCode: "ace", regionGroup: "East and Southeast Asia", primaryRegion: "Indonesia", tier: "EXPERIMENTAL_VERIFY" },
  { id: "tagalog", englishName: "Tagalog", autonym: "Tagalog", isoCode: "tl", regionGroup: "East and Southeast Asia", primaryRegion: "Philippines", tier: "STRONG" },
  { id: "filipino", englishName: "Filipino", autonym: "Filipino", isoCode: "fil", regionGroup: "East and Southeast Asia", primaryRegion: "Philippines", tier: "STRONG" },
  { id: "cebuano", englishName: "Cebuano", autonym: "Cebuano", isoCode: "ceb", regionGroup: "East and Southeast Asia", primaryRegion: "Philippines", tier: "GOOD_PRACTICAL" },
  { id: "ilocano", englishName: "Ilocano", autonym: "Ilokano", isoCode: "ilo", regionGroup: "East and Southeast Asia", primaryRegion: "Philippines", tier: "GOOD_PRACTICAL" },
  { id: "hiligaynon", englishName: "Hiligaynon", autonym: "Ilonggo", isoCode: "hil", regionGroup: "East and Southeast Asia", primaryRegion: "Philippines", tier: "EXPERIMENTAL_VERIFY" },
  { id: "waray", englishName: "Waray", autonym: "Winaray", isoCode: "war", regionGroup: "East and Southeast Asia", primaryRegion: "Philippines", tier: "EXPERIMENTAL_VERIFY" },
  { id: "kapampangan", englishName: "Kapampangan", autonym: "Kapampangan", isoCode: "pam", regionGroup: "East and Southeast Asia", primaryRegion: "Philippines", tier: "EXPERIMENTAL_VERIFY" },
  { id: "pangasinan", englishName: "Pangasinan", autonym: "Pangasinan", isoCode: "pag", regionGroup: "East and Southeast Asia", primaryRegion: "Philippines", tier: "EXPERIMENTAL_VERIFY" },
  { id: "tetum", englishName: "Tetum", autonym: "Tetun", isoCode: "tet", regionGroup: "East and Southeast Asia", primaryRegion: "Timor-Leste", tier: "GOOD_PRACTICAL" },
  { id: "shan", englishName: "Shan", autonym: "လိၵ်ႈတႆး", isoCode: "shn", regionGroup: "East and Southeast Asia", primaryRegion: "Myanmar and Thailand", tier: "EXPERIMENTAL_VERIFY" },
  { id: "karen-s-gaw", englishName: "Karen S'gaw", autonym: "ကညီကျိာ်", isoCode: "ksw", regionGroup: "East and Southeast Asia", primaryRegion: "Myanmar and Thailand", tier: "EXPERIMENTAL_VERIFY" },
  { id: "chin-hakha", englishName: "Chin Hakha", autonym: "Laiholh", isoCode: "cnh", regionGroup: "East and Southeast Asia", primaryRegion: "Myanmar and diaspora", tier: "EXPERIMENTAL_VERIFY" },
  { id: "maori", englishName: "Maori", autonym: "Te reo Māori", isoCode: "mi", regionGroup: "Oceania", primaryRegion: "New Zealand", tier: "GOOD_PRACTICAL" },
  { id: "samoan", englishName: "Samoan", autonym: "Gagana Samoa", isoCode: "sm", regionGroup: "Oceania", primaryRegion: "Samoa and diaspora", tier: "GOOD_PRACTICAL" },
  { id: "tongan", englishName: "Tongan", autonym: "Lea faka-Tonga", isoCode: "to", regionGroup: "Oceania", primaryRegion: "Tonga and diaspora", tier: "GOOD_PRACTICAL" },
  { id: "fijian", englishName: "Fijian", autonym: "Na vosa vaka-Viti", isoCode: "fj", regionGroup: "Oceania", primaryRegion: "Fiji", tier: "GOOD_PRACTICAL" },
  { id: "fiji-hindi", englishName: "Fiji Hindi", autonym: "Fiji Baat", isoCode: "hif", regionGroup: "Oceania", primaryRegion: "Fiji", tier: "EXPERIMENTAL_VERIFY" },
  { id: "hawaiian", englishName: "Hawaiian", autonym: "ʻŌlelo Hawaiʻi", isoCode: "haw", regionGroup: "Oceania", primaryRegion: "Hawaii", tier: "GOOD_PRACTICAL" },
  { id: "tahitian", englishName: "Tahitian", autonym: "Reo Tahiti", isoCode: "ty", regionGroup: "Oceania", primaryRegion: "French Polynesia", tier: "EXPERIMENTAL_VERIFY" },
  { id: "tok-pisin", englishName: "Tok Pisin", autonym: "Tok Pisin", isoCode: "tpi", regionGroup: "Oceania", primaryRegion: "Papua New Guinea", tier: "GOOD_PRACTICAL" },
  { id: "hiri-motu", englishName: "Hiri Motu", autonym: "Hiri Motu", isoCode: "ho", regionGroup: "Oceania", primaryRegion: "Papua New Guinea", tier: "EXPERIMENTAL_VERIFY" },
  { id: "bislama", englishName: "Bislama", autonym: "Bislama", isoCode: "bi", regionGroup: "Oceania", primaryRegion: "Vanuatu", tier: "GOOD_PRACTICAL" },
  { id: "marshallese", englishName: "Marshallese", autonym: "Kajin M̧ajeļ", isoCode: "mh", regionGroup: "Oceania", primaryRegion: "Marshall Islands", tier: "EXPERIMENTAL_VERIFY" },
  { id: "palauan", englishName: "Palauan", autonym: "Tekoi er a Belau", isoCode: "pau", regionGroup: "Oceania", primaryRegion: "Palau", tier: "EXPERIMENTAL_VERIFY" },
  { id: "chamorro", englishName: "Chamorro", autonym: "Finu' Chamoru", isoCode: "ch", regionGroup: "Oceania", primaryRegion: "Guam and Northern Mariana Islands", tier: "EXPERIMENTAL_VERIFY" },
  { id: "kiribati", englishName: "Kiribati", autonym: "Te taetae ni Kiribati", isoCode: "gil", regionGroup: "Oceania", primaryRegion: "Kiribati", tier: "EXPERIMENTAL_VERIFY" },
  { id: "tuvaluan", englishName: "Tuvaluan", autonym: "Te gana Tuvalu", isoCode: "tvl", regionGroup: "Oceania", primaryRegion: "Tuvalu", tier: "EXPERIMENTAL_VERIFY" },
  { id: "niuean", englishName: "Niuean", autonym: "Ko e vagahau Niuē", isoCode: "niu", regionGroup: "Oceania", primaryRegion: "Niue", tier: "EXPERIMENTAL_VERIFY" },
  { id: "cook-islands-maori", englishName: "Cook Islands Maori", autonym: "Māori Kūki 'Āirani", isoCode: "rar", regionGroup: "Oceania", primaryRegion: "Cook Islands", tier: "EXPERIMENTAL_VERIFY" },
  { id: "rotuman", englishName: "Rotuman", autonym: "Fäeag Rotuma", isoCode: "rtm", regionGroup: "Oceania", primaryRegion: "Fiji", tier: "EXPERIMENTAL_VERIFY" },
  { id: "haitian-creole", englishName: "Haitian Creole", autonym: "Kreyòl ayisyen", isoCode: "ht", regionGroup: "Americas and the Caribbean", primaryRegion: "Haiti and diaspora", tier: "GOOD_PRACTICAL" },
  { id: "papiamento", englishName: "Papiamento", autonym: "Papiamentu", isoCode: "pap", regionGroup: "Americas and the Caribbean", primaryRegion: "Caribbean Netherlands and Aruba", tier: "GOOD_PRACTICAL" },
  { id: "jamaican-patois", englishName: "Jamaican Patois", autonym: "Patwa", isoCode: "jam", regionGroup: "Americas and the Caribbean", primaryRegion: "Jamaica and diaspora", tier: "GOOD_PRACTICAL" },
  { id: "sranan-tongo", englishName: "Sranan Tongo", autonym: "Sranantongo", isoCode: "srn", regionGroup: "Americas and the Caribbean", primaryRegion: "Suriname", tier: "EXPERIMENTAL_VERIFY" },
  { id: "guarani", englishName: "Guarani", autonym: "Avañe'ẽ", isoCode: "gn", regionGroup: "Americas and the Caribbean", primaryRegion: "Paraguay and neighboring states", tier: "GOOD_PRACTICAL" },
  { id: "quechua-cusco", englishName: "Quechua Cusco", autonym: "Runasimi", isoCode: "quz", regionGroup: "Americas and the Caribbean", primaryRegion: "Peru", tier: "GOOD_PRACTICAL" },
  { id: "quechua-ayacucho", englishName: "Quechua Ayacucho", autonym: "Chanka Runasimi", isoCode: "quy", regionGroup: "Americas and the Caribbean", primaryRegion: "Peru", tier: "EXPERIMENTAL_VERIFY" },
  { id: "aymara", englishName: "Aymara", autonym: "Aymar aru", isoCode: "ay", regionGroup: "Americas and the Caribbean", primaryRegion: "Bolivia, Peru and Chile", tier: "GOOD_PRACTICAL" },
  { id: "nahuatl-central", englishName: "Nahuatl Central", autonym: "Nawatlahtolli", isoCode: "nhn", regionGroup: "Americas and the Caribbean", primaryRegion: "Mexico", tier: "EXPERIMENTAL_VERIFY" },
  { id: "yucatec-maya", englishName: "Yucatec Maya", autonym: "Maaya t'aan", isoCode: "yua", regionGroup: "Americas and the Caribbean", primaryRegion: "Mexico and Belize", tier: "EXPERIMENTAL_VERIFY" },
  { id: "k-iche", englishName: "K'iche'", autonym: "K'iche'", isoCode: "quc", regionGroup: "Americas and the Caribbean", primaryRegion: "Guatemala", tier: "EXPERIMENTAL_VERIFY" },
  { id: "kaqchikel", englishName: "Kaqchikel", autonym: "Kaqchikel", isoCode: "cak", regionGroup: "Americas and the Caribbean", primaryRegion: "Guatemala", tier: "EXPERIMENTAL_VERIFY" },
  { id: "q-eqchi", englishName: "Q'eqchi'", autonym: "Q'eqchi'", isoCode: "kek", regionGroup: "Americas and the Caribbean", primaryRegion: "Guatemala and Belize", tier: "EXPERIMENTAL_VERIFY" },
  { id: "mam", englishName: "Mam", autonym: "Qyol Mam", isoCode: "mam", regionGroup: "Americas and the Caribbean", primaryRegion: "Guatemala and Mexico", tier: "EXPERIMENTAL_VERIFY" },
  { id: "mapudungun", englishName: "Mapudungun", autonym: "Mapudungun", isoCode: "arn", regionGroup: "Americas and the Caribbean", primaryRegion: "Chile and Argentina", tier: "EXPERIMENTAL_VERIFY" },
  { id: "wayuu", englishName: "Wayuu", autonym: "Wayuunaiki", isoCode: "guc", regionGroup: "Americas and the Caribbean", primaryRegion: "Colombia and Venezuela", tier: "EXPERIMENTAL_VERIFY" },
  { id: "navajo", englishName: "Navajo", autonym: "Diné bizaad", isoCode: "nv", regionGroup: "Americas and the Caribbean", primaryRegion: "United States", tier: "EXPERIMENTAL_VERIFY" },
  { id: "cherokee", englishName: "Cherokee", autonym: "ᏣᎳᎩ", isoCode: "chr", regionGroup: "Americas and the Caribbean", primaryRegion: "United States", tier: "EXPERIMENTAL_VERIFY" },
  { id: "inuktitut", englishName: "Inuktitut", autonym: "ᐃᓄᒃᑎᑐᑦ", isoCode: "iu", regionGroup: "Americas and the Caribbean", primaryRegion: "Canada", tier: "GOOD_PRACTICAL" },
  { id: "greenlandic", englishName: "Greenlandic", autonym: "Kalaallisut", isoCode: "kl", regionGroup: "Americas and the Caribbean", primaryRegion: "Greenland", tier: "GOOD_PRACTICAL" },
  { id: "cree-plains", englishName: "Cree Plains", autonym: "Nēhiyawēwin", isoCode: "crk", regionGroup: "Americas and the Caribbean", primaryRegion: "Canada", tier: "EXPERIMENTAL_VERIFY" },
  { id: "ojibwe", englishName: "Ojibwe", autonym: "Anishinaabemowin", isoCode: "oj", regionGroup: "Americas and the Caribbean", primaryRegion: "Canada and United States", tier: "EXPERIMENTAL_VERIFY" },
  { id: "mi-kmaq", englishName: "Mi'kmaq", autonym: "Mi'kmawi'simk", isoCode: "mic", regionGroup: "Americas and the Caribbean", primaryRegion: "Canada", tier: "EXPERIMENTAL_VERIFY" },
  { id: "mohawk", englishName: "Mohawk", autonym: "Kanien'kéha", isoCode: "moh", regionGroup: "Americas and the Caribbean", primaryRegion: "Canada and United States", tier: "EXPERIMENTAL_VERIFY" },
  { id: "lakota", englishName: "Lakota", autonym: "Lakȟótiyapi", isoCode: "lkt", regionGroup: "Americas and the Caribbean", primaryRegion: "United States", tier: "EXPERIMENTAL_VERIFY" },
  { id: "hopi", englishName: "Hopi", autonym: "Hopilàvayi", isoCode: "hop", regionGroup: "Americas and the Caribbean", primaryRegion: "United States", tier: "EXPERIMENTAL_VERIFY" },
  { id: "central-alaskan-yupik", englishName: "Central Alaskan Yupik", autonym: "Yugtun", isoCode: "esu", regionGroup: "Americas and the Caribbean", primaryRegion: "United States", tier: "EXPERIMENTAL_VERIFY" },
  { id: "innu-aimun", englishName: "Innu Aimun", autonym: "Innu-aimun", isoCode: "moe", regionGroup: "Americas and the Caribbean", primaryRegion: "Canada", tier: "EXPERIMENTAL_VERIFY" },
  { id: "garifuna", englishName: "Garifuna", autonym: "Garífuna", isoCode: "cab", regionGroup: "Americas and the Caribbean", primaryRegion: "Central America and Caribbean", tier: "EXPERIMENTAL_VERIFY" },
  { id: "miskito", englishName: "Miskito", autonym: "Miskitu", isoCode: "miq", regionGroup: "Americas and the Caribbean", primaryRegion: "Nicaragua and Honduras", tier: "EXPERIMENTAL_VERIFY" },
  { id: "nheengatu", englishName: "Nheengatu", autonym: "Nheengatu", isoCode: "yrl", regionGroup: "Americas and the Caribbean", primaryRegion: "Brazil", tier: "EXPERIMENTAL_VERIFY" },
  { id: "yanomami", englishName: "Yanomami", autonym: "Yanomamö", isoCode: "guu", regionGroup: "Americas and the Caribbean", primaryRegion: "Brazil and Venezuela", tier: "EXPERIMENTAL_VERIFY" },
  { id: "warao", englishName: "Warao", autonym: "Warao", isoCode: "wba", regionGroup: "Americas and the Caribbean", primaryRegion: "Venezuela and Guyana", tier: "EXPERIMENTAL_VERIFY" }
];

/** Case/diacritic-loose match by English name, autonym or ISO code. */
export function findTranslationLanguage(query: string): TranslationLanguageEntry | null {
  const needle = query.trim().toLowerCase();
  if (!needle) return null;
  return (
    TRANSLATION_LANGUAGE_CATALOG.find((entry) => entry.isoCode.toLowerCase() === needle) ??
    TRANSLATION_LANGUAGE_CATALOG.find((entry) => entry.englishName.toLowerCase() === needle || entry.autonym.toLowerCase() === needle) ??
    TRANSLATION_LANGUAGE_CATALOG.find((entry) => entry.englishName.toLowerCase().includes(needle)) ??
    null
  );
}
