import { readFileSync } from "node:fs";
import path from "node:path";
import sharp from "sharp";
import { PrismaClient } from "@prisma/client";
import * as mod from "../../src/lib/studio/services/phash.ts";
const ph: any = (mod as any).default ?? mod;
const prisma = new PrismaClient();
const [title, key, out] = [process.argv[2], process.argv[3], process.argv[4] ?? "diag.png"];
const seg = await prisma.studioSegment.findFirst({ where: { key, template: { title: { contains: title } } } });
const frame = await prisma.studioAsset.findUnique({ where: { id: seg!.frameAssetId! } });
const bytes = readFileSync(path.join("storage/studio", frame!.storageKey));
const meta = await sharp(bytes).metadata();
const cleaned = await sharp(bytes).extract({ left: 0, top: 0, width: meta.width!, height: Math.round(meta.height! * 0.8) }).jpeg().toBuffer();
const hashes = await ph.frameHashes(cleaned);
const index = JSON.parse(readFileSync("storage/studio/shutterstock-index/index.json", "utf8"));
const locals = Object.values(index).filter((e: any) => e.localFile) as any[];
const scored = locals.map((e) => ({ e, d: ph.bestDistance(hashes, BigInt("0x" + e.hash)) })).sort((a, b) => a.d - b.d).slice(0, 6);
console.log(scored.map((s) => `${s.e.id} d=${s.d}`).join("  "));
const tiles = [await sharp(cleaned).resize(320, 200, { fit: "cover" }).toBuffer()];
for (const s of scored) tiles.push(await sharp(s.e.localFile).rotate().resize(320, 200, { fit: "cover" }).toBuffer());
await sharp({ create: { width: 320 * tiles.length, height: 200, channels: 3, background: "#000" } }).composite(tiles.map((t, i) => ({ input: t, left: i * 320, top: 0 }))).png().toFile(out);
await prisma.$disconnect();
